# The URL the site will be built for
base_url = "https://ericregina.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
title = "ericregina.com"
theme = "gruv-terminus"

# The default author for pages
author = "Eric Regina"


# The taxonomies to be rendered for the site and their configuration.
taxonomies = [{ name = "tags", feed = true }] # each tag will have its own feed

[markdown]
# Whether to do syntax highlighting
# Theme can be customized by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]

# Basic information
author = "Eric Regina"

main_menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "about", url = "about", trailing_slash = true },
    { name = "github", url = "https://github.com/ericreg", new_tab = true },
]

socials = [
    { name = "email", url = "mailto:eregina92@gmail.com" },
    { name = "github", url = "https://github.com/ericreg" },
    { name = "linkedin", url = "https://www.linkedin.com/in/ericregina" },
    { name = "discord", url = "https://www.discord.com/users/385938772535279617" },

]


# Whether to support KaTeX globally
# katex = true



# The options below are used to refer to the expressions on the pages, and you
# can custom the contents as needed in your language.
[extra.expressions]
home = "Home" # The homepage's name
pinned = "Pinned" # On the header of the post list
written_by = "Written by" # Like: Written by Aaran Xu
on = "on" # Like: on May 3, 2021
top = "Top" # Go to the top of the page in the post
tags = "Tags" # In the page of Tags

# The contents of the 404 page
p404 = "404: Page not found"
p404_info = "Oops! We can't seem to find the page you are looking for."
p404_back_home_start = "Let's"
p404_back_home_with_link = "head back home"
p404_back_home_end = "."
