# The URL the site will be built for
base_url = "https://ericregina.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "ericregina.com"

# Custom theme from https://github.com/ericreg/zola_docsascode_theme.git 
theme = "tale-zola"

# The taxonomies to be rendered for the site and their configuration.
taxonomies = [{ name = "tags", feed = true }] # each tag will have its own feed

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-mirage"

[extra]
# Basic infomation
author = "Eric Regina"
github = "https://github.com/ericreg"

# Set date format in the site
timeformat = "%B %e, %Y" # e.g. June 14, 2021

# Whether to support KaTeX globally
katex = true

# Whether to use Disqus globally and set to your disqus id
# or you can enable the disqus on per post page with `extra.disqus` option
disqus = true
disqus_id = "ericreg"

## Open Graph + Twitter Cards
[extra.seo]
# this image will be used as fallback if a page has no image of its own
image = "tale.png"
image_height = 0
image_width = 0
og_locale = "en_US"

# Menu items
[[extra.menu]]
name = "Posts"
url = "/"

[[extra.menu]]
name = "Tags"
url = "tags"

[[extra.menu]]
name = "About"
url = "about"

[extra.footer]
start_year = "2020" # start year of the site
end_year = "2021" # end year of the site
info = "Made with <a href=\"https://www.getzola.org\">Zola</a> with <a href=\"https://github.com/aaranxu/tale-zola\">Tala-Zola</a> theme."


# The options below are used to refer to the expressions on the pages, and you
# can custom the contents as needed in your language.
[extra.expressions]
home = "Home" # The homepage's name
pinned = "Pinned" # On the header of the post list
written_by = "Written by" # Like: Written by Aaran Xu
on = "on" # Like: on May 3, 2021
top = "Top" # Go to the top of the page in the post
tags = "Tags" # In the page of Tags

# The contents of the 404 page
p404 = "404: Page not found"
p404_info = "Oops! We can't seem to find the page you are looking for."
p404_back_home_start = "Let's"
p404_back_home_with_link = "head back home"
p404_back_home_end = "."
